### ISSUE TITLE
Apostrophes are clobbered when string contains emoji + contraction

### ISSUE THREAD

**Issue by mtmcfarl** [wpeterson/emoji#38]
If I have a string ``` It's time to go home 🎉 ```, it will replace the apostrophe in It's with &#39.  Any way to keep the apostrophe as it is and convert the emoji?

``` It's time to go home 🎉 ``` => ```It&#39s time to go home :tada```  I'd like to see ``` It's time to go home :tada: ```.

I'm passing my string into the ```self.replace_unicode_moji_with_name``` method.

**Comment by wpeterson** [comment]
The unicode emoji to HTML/image emoji processing uses HTML escaping to make sure you're not injecting an XSS vulnerability during Emoji replacement, which is why characters like `'` are escaped.

The emoji gem using the standard `html_safe?` Ruby/Rails layer to recognize whether strings are safe for display as HTML or not - whether it's already been processed or escaped.

If you want to use your own HTML escaping or bypass the escaping within the emoji gem, you need to mark your strings as HTML safe before passing them to the library - otherwise they will be escaped.
